modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/FarmingForBlockheads/issues"

[[mods]]
modId="farmingforblockheads"
version="${mod_version}"
displayName="Farming for Blockheads"
displayURL="https://mods.twelveiterations.com/mc/trashslot"
logoFile="farmingforblockheads-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adds a seed market with a search bar and a scrolling grid and more farming utilities.
'''

[[dependencies.farmingforblockheads]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.farmingforblockheads]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.farmingforblockheads]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
